"""Created query, listing, review tables

Revision ID: 510a00479353
Revises: 
Create Date: 2022-07-25 21:09:06.677759

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '510a00479353'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('listing',
    sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('num_rating', sa.Integer(), nullable=True),
    sa.Column('num_sold', sa.Integer(), nullable=True),
    sa.Column('shop_id', sa.BigInteger(), nullable=True),
    sa.Column('item_id', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('query',
    sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('term', sa.String(), nullable=True),
    sa.Column('frequency', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_query_term'), 'query', ['term'], unique=False)
    op.create_table('QueryListing',
    sa.Column('query_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('listing_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['listing_id'], ['listing.id'], ),
    sa.ForeignKeyConstraint(['query_id'], ['query.id'], )
    )
    op.create_table('review',
    sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('listing_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['listing_id'], ['listing.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_comment'), 'review', ['comment'], unique=False)
    op.create_index(op.f('ix_review_model'), 'review', ['model'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_model'), table_name='review')
    op.drop_index(op.f('ix_review_comment'), table_name='review')
    op.drop_table('review')
    op.drop_table('QueryListing')
    op.drop_index(op.f('ix_query_term'), table_name='query')
    op.drop_table('query')
    op.drop_table('listing')
    # ### end Alembic commands ###
